// <auto-generated />
using crud_c_sharp_sqlite.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace crud_c_sharp_sqlite.Migrations
{
    [DbContext(typeof(ContextoBanco))]
    partial class RetratoModeloContextoBanco : ModelSnapshot
    {   // Código auto gerado pelo DotNet.
        // Método que builda o model do banco.
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            // Método que entra com as informações na tabela.
            modelBuilder.Entity("crud_c_sharp_sqlite.Models.Student", b =>
                {
                    // Auto increment do ID.
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    // IsRquired(): O mesmo que not null.
                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    // Definindo a chave ID.
                    b.HasKey("Id");

                    // Informa a tabela que será inserido essas informações.
                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
